version: "3.7"
services:
  greet_service:
    image: dillonys/grpc-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    web_proxy:
      image:  envoyproxy/envoy:v1.14.1
      ports:
        - "8080:8080"
        - "9901:9901"
      volumes:
        - "./envoy.yaml:/etc/envoy/envoy.yaml:ro"
